config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  :path_names => {
    :sign_in       => 'login',
    :sign_out      => 'logout',
    :sign_up       => 'register',
    :registration  => 'account',
    :password      => 'user/password'
  },
  :controllers => {
    :sessions      => 'authentication',
    :registrations => 'account'
  }

  resources :states, only: [:index], shallow: true do
    resources :counties, only: [:index] do
      resources :municipalities, only: [:index]
    end
  end

  authenticate :user do
    resources :cases
    resources :parties
    resources :documents

    resources :clients, shallow: true do
      resources :client_contacts
    end
    resources :client_contacts, only: [:index]

    resources :jobs, shallow: true do
      resources :services, shallow: true do
        resources :attempts
        resources :affidavits
      end
    end
    resources :affidavits, only: [:index]
    resources :attempts, only: [:index]
    resources :services, only: [:index]

    get 'organization/edit' => 'organizations#edit'
    patch 'organization' => 'organizations#update'
  end

  authenticated :user do
    get 'dashboard/fill_data'
    get 'dashboard/clear_data'

    root :to => 'dashboard#index', :as => :organization_root
  end

  root :to => 'welcome#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @case_count    = Case.count
    @job_count     = Job.count
    @service_count = Service.count
    @client_count  = Client.count
  end

  def fill_data
    DataFill.new().fill_tenant
    redirect_to organization_root_path
  end

  def clear_data
    DataFill.new().clear_tenant
    redirect_to organization_root_path
  end
end

app/views/dashboard/index.html.slim
.row
  .col-lg-12
    h1.page-header= "#{current_user.organization.name} Dashboard"

.row
  .col-lg-3.col-md-6
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-file-text-o.fa-5x
          .col-xs-9.text-right
            .huge= @case_count
            div Cases
      a href="#"
      .panel-footer
        = link_to 'View Cases', cases_path, class: 'pull-left'
        = link_to cases_path, class: 'pull-right' do
          i.fa.fa-arrow-circle-right
        .clearfix
  .col-lg-3.col-md-6
    .panel.panel-green
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-tasks.fa-5x
          .col-xs-9.text-right
            .huge= @job_count
            div Jobs
      a href="#"
      .panel-footer
        = link_to 'View Jobs', jobs_path, class: 'pull-left'
        = link_to jobs_path, class: 'pull-right' do
          i.fa.fa-arrow-circle-right
        .clearfix
  .col-lg-3.col-md-6
    .panel.panel-yellow
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-paper-plane.fa-5x
          .col-xs-9.text-right
            .huge= @service_count
            div Services
      a href="#"
      .panel-footer
        = link_to 'View Services', services_path, class: 'pull-left'
        = link_to services_path, class: 'pull-right' do
          i.fa.fa-arrow-circle-right
        .clearfix
  .col-lg-3.col-md-6
    .panel.panel-red
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-users.fa-5x
          .col-xs-9.text-right
            .huge= @client_count
            div Clients
      a href="#"
      .panel-footer
        = link_to 'View Clients', clients_path, class: 'pull-left'
        = link_to clients_path, class: 'pull-right' do
          i.fa.fa-arrow-circle-right
        .clearfix

.row
  .col-lg-12
    = link_to 'Add New Case', new_case_path, class: 'btn btn-lg btn-primary'
    br
    br
    .btn-group.btn-group-sm
      = link_to 'Fill Data', dashboard_fill_data_path, class: 'btn btn-default'
      = link_to 'Reset Data', dashboard_clear_data_path, class: 'btn btn-default'