config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  :path_names => {
    :sign_in       => 'login',
    :sign_out      => 'logout',
    :sign_up       => 'register',
    :registration  => 'account',
    :password      => 'user/password'
  },
  :controllers => {
    :sessions      => 'authentication',
    :registrations => 'account'
  }

  resources :states, only: [:index], shallow: true do
    resources :counties, only: [:index] do
      resources :municipalities, only: [:index]
    end
  end

  authenticate :user do
    resources :cases
    resources :parties
    resources :documents

    resources :clients, shallow: true do
      resources :client_contacts
    end
    resources :client_contacts, only: [:index]

    resources :jobs, shallow: true do
      resources :services, shallow: true do
        resources :attempts
        resources :affidavits
      end
    end
    resources :affidavits, only: [:index]
    resources :attempts, only: [:index]
    resources :services, only: [:index]

    get 'organization/edit' => 'organizations#edit'
    patch 'organization' => 'organizations#update'
  end

  authenticated :user do
    get 'dashboard/fill_data'
    get 'dashboard/clear_data'

    root :to => 'dashboard#index', :as => :organization_root
  end

  root :to => 'welcome#index'

end

app/views/shared/_footer.html.slim
= react_component 'ModalWrapper', props: {}, server_side: true 

app/views/shared/_header.html.slim
#header.nav.navbar.navbar-default.navbar-static-top(role="navigation" style=("margin-bottom: 0") data-turbolinks-permanent)
  .navbar-header
    button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    - if user_signed_in?
      = link_to Rails.application.class.parent_name, organization_root_path, class: 'navbar-brand'
    - else
      = link_to Rails.application.class.parent_name, root_path, class: 'navbar-brand'

  ul.nav.navbar-top-links.navbar-right
    - if !user_signed_in?
      li= active_link_to "Login", new_user_session_path
      li= button_to "Sign Up", new_user_registration_path, :method => :get, class: 'btn btn-default navbar-btn'
    - else
      li= link_to organization_root_path do
        i.fa.fa-bar-chart-o.fa-fw
        | Dashboard
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#"
          i.fa.fa-user.fa-fw
          i.fa.fa-caret-down
        ul.dropdown-menu.dropdown-user
          li= link_to organization_edit_path do
            i.fa.fa-user.fa-fw
            | Organization Settings
          li= link_to edit_user_registration_path do
            i.fa.fa-gear.fa-fw
            | User Settings
          li.divider
          li= link_to destroy_user_session_path, :method => :delete do
            i.fa.fa-sign-out.fa-fw
            | Logout

  - if user_signed_in?
    = render 'shared/sidebar'

app/views/shared/_sidebar.html.slim
#sidebar.navbar-default.sidebar(role="navigation" data-turbolinks-permanent)
  .sidebar-nav.navbar-collapse
    ul#side-menu.nav
      li.sidebar-search
        .input-group.custom-search-form
          input.form-control placeholder="Search..." type="text" /
          span.input-group-btn
            button.btn.btn-default type="button"
              i.fa.fa-search
        /! /input-group

      li= link_to organization_root_path, :active => :exclusive do
          i.fa.fa-bar-chart-o.fa-fw
          | Dashboard

      li
        a href="#"
          i.fa.fa-sitemap.fa-fw
          | Jobs & Cases
          span.fa.arrow
        ul.nav.nav-second-level
          li= link_to "Jobs", jobs_path
          li= link_to "Services", services_path

      li
        a href="#"
          i.fa.fa-files-o.fa-fw
          | Documents
          span.fa.arrow
        ul.nav.nav-second-level
          li= link_to 'Affidavits', affidavits_path

      li
        a href="#"
          i.fa.fa-server.fa-fw
          | Logs
          span.fa.arrow
        ul.nav.nav-second-level
          li= link_to 'Server Logs', attempts_path

      li
        a href="#"
          i.fa.fa-group.fa-fw
          | Cases, Clients & Parties
          span.fa.arrow
        ul.nav.nav-second-level
          li= link_to "Cases", cases_path
          li= link_to "Clients", clients_path
          li= link_to "Client Contacts", client_contacts_path
          li= link_to "Serving Parties", parties_path

      li= link_to organization_edit_path do
        i.fa.fa-gears.fa-fw
        | Organization Settings