config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '',
  :path_names => {
    :sign_in       => 'login',
    :sign_out      => 'logout',
    :sign_up       => 'register',
    :registration  => 'account',
    :password      => 'user/password'
  },
  :controllers => {
    :sessions      => 'authentication',
    :registrations => 'account'
  }

  resources :states, only: [:index], shallow: true do
    resources :counties, only: [:index] do
      resources :municipalities, only: [:index]
    end
  end

  authenticate :user do
    resources :cases
    resources :parties
    resources :documents

    resources :clients, shallow: true do
      resources :client_contacts
    end
    resources :client_contacts, only: [:index]

    resources :jobs, shallow: true do
      resources :services, shallow: true do
        resources :attempts
        resources :affidavits
      end
    end
    resources :affidavits, only: [:index]
    resources :attempts, only: [:index]
    resources :services, only: [:index]

    get 'organization/edit' => 'organizations#edit'
    patch 'organization' => 'organizations#update'
  end

  authenticated :user do
    get 'dashboard/fill_data'
    get 'dashboard/clear_data'

    root :to => 'dashboard#index', :as => :organization_root
  end

  root :to => 'welcome#index'

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  belongs_to :service

  validates :service,      presence: true
  validates :user_id,      presence: true
  validates :address,      presence: true
  validates :attempted_at, presence: true

  def user
    User.find(self.user_id)
  end

  def server_name
    self.user.name
  end

  def date_attempted
    self.attempted_at.strftime("%b #{self.attempted_at.day.ordinalize}, %Y") if self.attempted_at
  end

  def time_attempted
    self.attempted_at.strftime("%I:%M%p") if self.attempted_at
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :set_attempt, only: [:show, :edit, :update, :destroy]

  respond_to :json, only: [:index, :show, :new, :create]

  has_scope :client_id

  # GET /attempts
  def index
    @attempts = apply_scopes(Attempt).all

    respond_to do |format|
      format.html { render react_component: 'TableWrapper', props: table_props }
      format.json { render :json => select_format(@attempts) }
    end
  end

  # GET /attempts/1
  def show
    form_repsonse(form_props)
  end

  # GET /attempts/new
  def new
    @service = Service.find(params[:service_id])
    @attempt = Attempt.new({ service_id: @service_id })
    form_repsonse(form_props)
  end

  # GET /attempts/1/edit
  def edit
    form_repsonse(form_props)
  end

  # POST /attempts
  def create
    @attempt = Attempt.new(attempt_params)

    if @attempt.save
      render json: { resource: @attempt, redirect: service_attempts_path() }
    else
      render json: { attempt: @attempt.errors }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /attempts/1
  def update
    if @attempt.update(attempt_params)
      render json: { resource: @attempt, redirect: service_attempts_path() }
    else
      render json: { attempt: @attempt.errors }, status: :unprocessable_entity
    end
  end

  # DELETE /attempts/1
  def destroy
    @attempt.destroy
    redirect_to service_attempts_url, notice: 'Attempt was successfully destroyed.'
  end

private

  def set_attempt
    @attempt = Attempt.find(params[:id])
  end

  def attempt_params
    params.require(:attempt).permit(:service_id, :user_id, :address, :attempted_at, :successful, :mileage, :payment, :notes)
  end

  def form_props
    clients = select_format Client.all().order(:name)

    {
      :type     => 'attempts',
      :resource => @attempt,
      :action   => polymorphic_path([@service, @attempt]),
    }
  end

  def table_props
    {
      :sort_col => :created_at,
      :type     => 'attempts',
      :rows     => @attempts.map { |a| AttemptSerializer.new(a) },
      :columns => {
        :job_number     => 'Job #',
        :server_name    => 'Server',
        :party_name     => 'Service Party',
        :successful     => 'Successful',
        :date_attempted => 'Date',
        :time_attempted => 'Time',
        :address        => 'Address',
        :notes          => 'Notes',
        :actions        => ''
      }.to_a
    }
  end
end

app/views/attempts/_form.html.slim
= form_for @attempt do |f|
  - if @attempt.errors.any?
    #error_explanation
      h2 = "#{pluralize(@attempt.errors.count, "error")} prohibited this attempt from being saved:"
      ul
        - @attempt.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :service
    = f.text_field :service
  .field
    = f.label :organization_user
    = f.text_field :organization_user
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :attempted_at
    = f.datetime_select :attempted_at
  .field
    = f.label :successful
    = f.check_box :successful
  .field
    = f.label :mileage
    = f.number_field :mileage
  .field
    = f.label :payment
    = f.text_field :payment
  .field
    = f.label :notes
    = f.text_area :notes
  .actions = f.submit

app/views/attempts/edit.html.slim
h1 Editing attempt

== render 'form'

= link_to 'Show', @attempt
'|
= link_to 'Back', attempts_path

app/views/attempts/index.html.slim
h1 Listing attempts

table
  thead
    tr
      th Service
      th Organization user
      th Address
      th Attempted at
      th Successful
      th Mileage
      th Payment
      th Notes
      th
      th
      th

  tbody
    - @attempts.each do |attempt|
      tr
        td = attempt.service
        td = attempt.organization_user
        td = attempt.address
        td = attempt.attempted_at
        td = attempt.successful
        td = attempt.mileage
        td = attempt.payment
        td = attempt.notes
        td = link_to 'Show', attempt
        td = link_to 'Edit', edit_attempt_path(attempt)
        td = link_to 'Destroy', attempt, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Attempt', new_attempt_path

app/views/attempts/new.html.slim
h1 New attempt

== render 'form'

= link_to 'Back', attempts_path

app/views/attempts/show.html.slim
p#notice = notice

p
  strong Service:
  = @attempt.service
p
  strong Organization user:
  = @attempt.organization_user
p
  strong Address:
  = @attempt.address
p
  strong Attempted at:
  = @attempt.attempted_at
p
  strong Successful:
  = @attempt.successful
p
  strong Mileage:
  = @attempt.mileage
p
  strong Payment:
  = @attempt.payment
p
  strong Notes:
  = @attempt.notes

= link_to 'Edit', edit_attempt_path(@attempt)
'|
= link_to 'Back', attempts_path